### ISSUE TITLE
Book OTV Appointments

### ISSUE THREAD

**Issue by ahmer70** [stableway/anmeldung-berlin#25]
hi can you please gave attribute value example that i can set for Book OTV Appointments

<img width="557" alt="Screenshot 2024-02-19 at 10 01 35 PM" src="https://github.com/stableway/anmeldung-berlin/assets/57433886/01c11430-28dd-483b-a46f-d5227b48554f">

**Comment by daniel-cortez-stevenson** [comment]
> hi can you please gave attribute value example that i can set for Book OTV Appointments
> 
> 
> 
> <img width="557" alt="Screenshot 2024-02-19 at 10 01 35 PM" src="https://github.com/stableway/anmeldung-berlin/assets/57433886/01c11430-28dd-483b-a46f-d5227b48554f">
> 
> 

Check playwright.config.js for the Playwright Project "otv.berlin.de".

**Comment by daniel-cortez-stevenson** [comment]
@ahmer70 you can create an issue if you have a bug to report 👍
